// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNAv0GMtxQFbMnc8-6SpFi9dseBjncm3c',
    appId: '1:382194485189:web:2070ec672656759c4cadac',
    messagingSenderId: '382194485189',
    projectId: 'my-finance-ce47b',
    authDomain: 'my-finance-ce47b.firebaseapp.com',
    storageBucket: 'my-finance-ce47b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzVw3fY0IwHhB8IgCeC5I4fLXpiJ7c7U4',
    appId: '1:382194485189:android:ba056ab507230fd64cadac',
    messagingSenderId: '382194485189',
    projectId: 'my-finance-ce47b',
    storageBucket: 'my-finance-ce47b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu7IAqtriXDtctLWnAimsDJvRPCjv7HB0',
    appId: '1:382194485189:ios:29bd42579def90654cadac',
    messagingSenderId: '382194485189',
    projectId: 'my-finance-ce47b',
    storageBucket: 'my-finance-ce47b.appspot.com',
    iosBundleId: 'com.example.myfinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu7IAqtriXDtctLWnAimsDJvRPCjv7HB0',
    appId: '1:382194485189:ios:29bd42579def90654cadac',
    messagingSenderId: '382194485189',
    projectId: 'my-finance-ce47b',
    storageBucket: 'my-finance-ce47b.appspot.com',
    iosBundleId: 'com.example.myfinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNAv0GMtxQFbMnc8-6SpFi9dseBjncm3c',
    appId: '1:382194485189:web:f7e56882b9292f094cadac',
    messagingSenderId: '382194485189',
    projectId: 'my-finance-ce47b',
    authDomain: 'my-finance-ce47b.firebaseapp.com',
    storageBucket: 'my-finance-ce47b.appspot.com',
  );
}
